### ISSUE TITLE
FEATURE: Action buttons in View mode

### ISSUE THREAD

**Issue by SlimeDog** [TryHardDood/AdvancedKitsReloaded#26] opened 2017-04-26 20:36 UTC
Please consider adding action buttons (buy, edit, etc.) in View mode.

**Comment by benjaminforras** [comment] 2017-04-26 20:42
Duplicate of https://github.com/TryHardDood/AdvancedKitsReloaded/issues/21

**Closed as completed by benjaminforras** 2017-04-26 20:42 UTC
Labels: duplicate
