### ISSUE TITLE
Missing command: /kit give

### ISSUE THREAD

**Issue by SlimeDog** [TryHardDood/AdvancedKitsReloaded#25] opened 2017-04-26 20:34 UTC
## What steps will reproduce the problem?  
/kit give <player> <kit> 

## What were you expecting to happen? What happened instead?  
Expect: Receive the kit.
Result: Command not found.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.0.2

## What Spigot version are you using? *Type /version*  
1.11.2

## What plugins are you using? *Type /plugins*  
Many

## Additional information?  *(Did it work in previous versions? etc.)*
Worked in AKR 3.0.29-36 and previous.

**Comment by benjaminforras** [comment] 2017-04-26 20:41
Duplicate of https://github.com/TryHardDood/AdvancedKitsReloaded/issues/22

**Closed as completed by benjaminforras** 2017-04-26 20:41 UTC
Labels: duplicate
